### ISSUE TITLE
Custom Audience Triggers Empty Response Exception

### ISSUE THREAD

**Issue by JordanDalton** [facebook/facebook-php-ads-sdk#158] opened 2015-12-01 17:05 UTC
I'm attempting to create a custom audience based on the sample code at https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting/v2.5#create

My Code

````php
$fb_custom_audience = new CustomAudience( null, 'act_<REMOVED>' );

$fb_custom_audience->setData(array(
        CustomAudienceFields::NAME => 'My lookalike audience',
        CustomAudienceFields::SUBTYPE => CustomAudienceSubtypes::LOOKALIKE,
        CustomAudienceFields::ORIGIN_AUDIENCE_ID => '<REMOVED>',
        CustomAudienceFields::LOOKALIKE_SPEC => array(
        'type' => 'similarity',
        'country' => 'US',
    ),
));
$fb_custom_audience->create();
````

The origin_audience_id I'm using has an approximate_count of 20 which should trigger a "Source Audience is Too Small" exception but it throws a EmptyResponseException instead.

**Comment by pruno** [comment] 2015-12-01 17:56
can you please generate a curl equivalent of your requests and test the call with curl? This will tell us whether this is an SDK or API issue.

Enable the curl logger:
~~~php
use FacebookAds\Logger\CurlLogger;

Api::instance()->setLogger(new CurlLogger(fopen('<PATH_TO_FS>', 'w+')));
~~~

where <PATH_TO_FS> is a path that your webserver has writing permissions for.
all requests made with the SDK will be logged in their curl-equivalent form

**Comment by JordanDalton** [comment] 2015-12-01 18:07
````
curl \
  -F 'name=My lookalike audience' \
  -F 'subtype=LOOKALIKE' \
  -F 'origin_audience_id=<REMOVED>' \
  -F 'lookalike_spec={"type":"similarity","country":"US"}' \
  -F 'access_token=<removed>' \
  -F 'appsecret_proof=<removed>' \
  https://graph.facebook.com/v2.5/act_<REMOVED>/customaudiences
````

**Comment by JordanDalton** [comment] 2015-12-01 18:39
````
{"error":{"message":"(#2654) Source Audience is Too Small: There aren\u2019t enough people in your source in the country you chose. Please choose a country that includes at least 100 people in your source.","type":"OAuthException","code":2654,"fbtrace_id":"AvrpvHcCKZe"}}
````

**Comment by duliomatos** [comment] 2015-12-02 17:55
Hello @JordanDalton, I was not able to reproduce the empty response and from your curl response it looks like a transient problem. Does the issue still happens? Using your code with my own ad account the exception is correct on the latest SDK code:

```
Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#2654) Source Audience is Too Small: There aren’t enough people in your source in the country you chose. Please choose a country that includes at least 100 people in your source.' in /Users/duliomatos/Dev/AdsPhp/src/FacebookAds/Http/Exception/RequestException.php:137
```

**Comment by paulbain** [comment] 2015-12-02 18:06
can you message one of us with the full call (excluding the appsecret_proof)? It may be something odd with the origin audience or something like that

**Comment by JordanDalton** [comment] 2015-12-02 18:14
@paulbain what's the best way to message you?

**Comment by duliomatos** [comment] 2015-12-04 19:54
Hey @JordanDalton, lmk if the reported issue still happens on you code. thx

**Comment by JordanDalton** [comment] 2015-12-04 21:06
@duliomatos I'm still experiencing the issue.

**Comment by liorpr** [comment] 2015-12-07 15:58
Had the same issue.. this happens because the response is not parsed correctly and thus the SDK generates an empty response exception. It seems like it parses the response headers incorrectly, according to the curl version you're using...

**Comment by duliomatos** [comment] 2015-12-14 15:30
Hello @liorpr, thx! Can you share the curl version you were using? 

@JordanDalton: Can you share the curl version as well and check if upgrading solves it as suggested by @liorpr?

I'll check with the versions you guys are using, thank you both.

**Comment by JordanDalton** [comment] 2015-12-14 17:20
@duliomatos 

curl 7.37.1 

I'll work on upgrading curl and will get back to you.

**Comment by JordanDalton** [comment] 2015-12-14 18:33
@duliomatos 

I upgraded my virtual box (Laravel Homestead) to the latest version, which is running curl 7.35. No errors now when creating the custom audience.

**Comment by duliomatos** [comment] 2015-12-14 18:38
Gr8 @JordanDalton, I'll try with 7.37.1 to see if curl compatibility was the culprit and find a fix.

**Comment by liorpr** [comment] 2015-12-17 17:52
Using curl version 7.43 @duliomatos

**Comment by liorpr** [comment] 2015-12-23 13:41
Hi, any updates about this ?

**Comment by duliomatos** [comment] 2016-01-12 01:00
Tried different VM's and curl versions but not able to replicate. Closing this as this seems to be a bug on dependent libraries and not easily reproducible, pls open again if something similar crops up.

**Closed by duliomatos** 2016-01-12 01:00 UTC
