### ISSUE TITLE
Invalid parameter  while creating Ad at step 7

### ISSUE THREAD

**Issue by rrb11** [facebook/facebook-php-ads-sdk#276] opened 2017-01-15 06:25 UTC
FacebookAds\Http\Exception\AuthorizationException

Invalid parameter

**Comment by JiamingFB** [comment] 2017-01-17 19:18
Hello @rrb11 ,

AuthorizationException could be related to an invalid/lack-of-permission access token.
Do you have more details about the issue?

You can try to use [API Explorer](https://developers.facebook.com/tools/explorer) to run the request and debug so that we know if it's caused by SDK bug or something else.

Thanks,
Jiaming

**Comment by jamespshields** [comment] 2017-01-18 17:40
When I got this error it turns out there was nothing wrong with authorization. I resolved it by commenting out parameters until I identified the 'invalid' one.

**Comment by JiamingFB** [comment] 2017-01-26 20:44
Closing the issue.

This is typically caused by an invalid access_token, insufficient permissions, or invalid parameters.

If you believe that the issue is caused by an SDK or API bug, feel free to reopen the issue with more details.

Thanks!

**Closed by JiamingFB** 2017-01-26 20:44 UTC
