### ISSUE TITLE
Ad Stats Report

### ISSUE THREAD

**Issue by sandy69** [facebook/facebook-php-ads-sdk#58] opened 2015-01-07 00:31 UTC
Hello,

I upgraded to php version 5.4.36. Installed the composer and installed the The Facebook Ads API SDK and even after that, when I execute the php script, I get the below error

PHP Fatal error: Class 'FacebookAds\Object\AdAccount' not found in /tmp/vendor/facebook/php-ads-sdk/src/FacebookAds/fb.php on line 3

PHP Code

<?php
use FacebookAds\Object\AdAccount;
$account = new AdAccount();
$account->name = 'act_5291585038833333';
echo $account->name;

$params = array(
'date_preset'=>'last_28_days',
'data_columns'=>"['adgroup_id','actions','spend']",
);

$stats = $account->getReportsStats(null, $params);

foreach($stats as $stat) {
echo $stat->impressions;
echo $stat->actions;
}

any information will be highly appreciated

**Comment by pruno** [comment] 2015-01-07 14:24
Duplicate of https://github.com/facebook/facebook-php-ads-sdk/issues/51

**Closed by pruno** 2015-01-07 14:24 UTC
Labels: duplicate
